### ISSUE TITLE
Add drivers for HP printers

### ISSUE THREAD

**Issue by ondrejholy** [negativo17/uld#1]
I’ve just bought a new printer and found out that also some HP printers need ULD.  Unfortunately, the HP drivers are not part of your package as they are distributed separately. It is not fully clear to me why, maybe licensing? I have tried the following and my HP printer works nicely:

```
$ sudo dnf install uld
$ wget https://ftp.hp.com/pub/softlib/software13/printers/MFP170/uld-hp_V1.00.39.12_00.15.tar.gz
$ tar -xvzf uld-hp_V1.00.39.12_00.15.tar.gz
$ cd uld
$ sudo cp noarch/share/ppd/*.ppd /usr/share/cups/model/uld/
$ sudo cp noarch/share/ppd/cms/*.cts /usr/share/cups/model/uld/cms/
$ sudo mkdir -p /opt/hp/scanner/share
$ sudo cp noarch/oem.conf /opt/hp/scanner/share/oem.conf
```

What do you think about adding the `.ppd` and `.cts` files for HP printers to your package?

**Comment by scaronni** [comment]
Congrats, you just found a new `uld` tarball, I thought it was dead:

```
$ cat uld/noarch/.version-printer uld/noarch/.version-scanner
1.00.39.12
1.00.39.12
$ cat uld.old/noarch/.version-printer uld.old/noarch/.version-scanner
1.00.39.1
1.00.39.1
```

It adds `aarch64` and `mips64` support, but drops all Samsung branded printers.

I will combine the two tarballs. Can you please tell me the page you got it from so I can track updates?

Please note my old Samsung printer/scanner is dead and I no longer have hardware to test.

**Comment by scaronni** [comment]
> Can you please tell me the page you got it from so I can track updates?

Nevermind, I've found what I was looking for and I updated the SPEC file with new information.

**Comment by scaronni** [comment]
All the changes are here, updated package will be online soon: https://github.com/negativo17/uld/commit/57ed90b8b42ccff4d4f1c9e53ecca0004602b57a

Do you know of any package I can take as a reference that is using AppData to let PackageKit find drivers based on hardware id parsing ppd files?

**Comment by scaronni** [comment]
So I can do something like this, for example:

- https://github.com/negativo17/nvidia-driver/blob/master/nvidia-driver.spec#L249-L251
- https://github.com/negativo17/intel-media-driver/blob/master/intel-media-driver.spec#L70-L72

**Comment by ondrejholy** [comment]
Great news, thanks for the package update! I am going to test it...

I got that link from https://support.hp.com/cz-cs/drivers/selfservice/hp-color-laser-mfp-170-printer-series/24494365/model/24494366.

When I am looking at the changes, haven't you forgotten to update also `oem.conf` handling to be installed in `/opt/hp` also?

It would be nice to update also the description in `uld.xml`. 

It would be super cool to add integration with PackageKit. I have just gone over some package drivers in Fedora, but none of them contains  the `.metainfo.xml` file  :thinking:

**Comment by ondrejholy** [comment]
Printing works, but the `oem.conf` handling is broken and I don't see the scanner (except the eSCL one) . The  `/opt/samsung/scanner/share` directory contains the `oem.conf` from the HP package and `/opt/hp` is empty. When I put the `oem.conf` in `/opt/hp/scanner/share`, the scanner is found and works...

**Comment by scaronni** [comment]
> Printing works, but the `oem.conf` handling is broken and I don't see the scanner (except the eSCL one) . The `/opt/samsung/scanner/share` directory contains the `oem.conf` from the HP package and `/opt/hp` is empty. When I put the `oem.conf` in `/opt/hp/scanner/share`, the scanner is found and works...

Right, forgot that part. Need to figure out what needs to be in the `oem.conf` file for BOTH vendors, otherwise 2 different packages are needed. This is particularly tricky considering now I have no hardware to test.

These are the two `oem.conf` files:
```
VENDOR=HP
VID=03F0
PIDS="AA2A CE2A C02A EB2A F22A"
```
```
VENDOR=Samsung
VID=04e8
PIDS="3425 341c 342a 343d 3456 345a 3427 343a 3428 343b 3455 3421 3439 3444 343f 344e 3431 345c 344d 3462 3464 3461 3460 340e 3435 340f 3441 344f 3413 341b 342e 3426 342b 3433 3440 3434 345b 3457 341f 3453 344b 3409 3412 3419 342c 343c 3432 342d 3430 342f 3446 341a 3437 3442 3466 340d 341d 3420 3429 3443 3438 344c 345d 3463 3465 3450 3468 3469 3467 346b 346a 346e 3471 3472 347d 347c 347e 3481 3482 3331 3332 3483 3484 3485 3478 3325 3327 346f 3477 3324 3326 3486 3487 3489"
```

May I ask you to figure out  why scanning needs `oem.conf` and if there is a way to combine the information from the two? Otherwise we need two different packages with all sort of issues if you happen to need both a samsug and an hp printer at the same time.

**Comment by ondrejholy** [comment]
I'm sorry for the confusion. I've just made some other tests and the scanner is correctly discovered regardless of the content of the `oem.conf` files. The printer is just sometimes not found by `scanimage -L`, though it is not related to `oem.conf`, so I would guess this is rather something with network or simple bug in smfp.

Why do you think that we have to combine those files? The `libsane-smfp.so` library seems to be able to handle different vendors as the hp/samsung string is not hardcoded:
```
$ strings uld/x86_64/libsane-smfp.so.1.0.1 | grep oem.conf
/opt/%s/scanner/share/oem.conf
```

So I hope it should be ok to simply put `oem.conf` from the samsung tarball under `/opt/samsung` and the hp one under `/opt/hp`.

I use the printer over network, not over USB. I guess that those files might be useful when connected over USB, but I am totally out of capacity to make some other experiments over USB...

**Comment by ondrejholy** [comment]
But it is true that there are two separate packages https://aur.archlinux.org/pkgbase/samsung-unified-driver and https://aur.archlinux.org/packages/hpuld for Arch. Also https://www.bchemnet.com/suldr/ repository for Debian doesn't contain HP printers with the following explanation:

> Note that HP is releasing new drivers for some new HP printers based on the Samsung hardware, but I have no idea if those newer drivers are an improvement or if they will work with the older Samsung printers. For that reason, as well as the issues raised in the previous update below (which also apply to the newest HP drivers), I do not anticpate providing those files through this repository.

So maybe it is not that easy. I'm really sad that corporations like HP can't handle this better and also pissed at myself that I bought such printer...

**Comment by scaronni** [comment]
From what I've seen on the binaries they have just been rebuilt, so it should not be an issue. I know from the logs that many other people are downloading the package, so let's see. So far no feedback, which means it could be working.

> I'm sorry for the confusion. I've just made some other tests and the scanner is correctly discovered regardless of the content of the `oem.conf` files. The printer is just sometimes not found by `scanimage -L`, though it is not related to `oem.conf`, so I would guess this is rather something with network or simple bug in smfp.

This was happening to me as well, it's just not very reliable. Sometimes the printer would to sleep and that was not working as well.

> Why do you think that we have to combine those files? The `libsane-smfp.so` library seems to be able to handle different vendors as the hp/samsung string is not hardcoded:
> 
> $ strings uld/x86_64/libsane-smfp.so.1.0.1 | grep oem.conf
> /opt/%s/scanner/share/oem.conf

We would need to know what the `%s` means, I think it's just the base folder from where stuff is placed.

> So I hope it should be ok to simply put `oem.conf` from the samsung tarball under `/opt/samsung` and the hp one under `/opt/hp`.
> 
> I use the printer over network, not over USB. I guess that those files might be useful when connected over USB, but I am totally out of capacity to make some other experiments over USB...

Honestly, I would try completely without the file :D.

I'll have a look but standby until someone comes up with a proper bug.

**Comment by scaronni** [comment]
Ah, bingo, you were right:
```
$ strings libsane-smfp.so.1.0.1 | grep vendor:
vendor:          %s
	vendor: <%s>
vendor:         %s
```
But let's see if it works without first.

**Comment by scaronni** [comment]
Both changes done here: https://github.com/negativo17/uld/commit/25a3e82d59d4ed5cabcf13c3ecf685d5f8d08083

I will close this issue, if you have any other issue please open another one.
Thanks for reporting!

**Comment by ondrejholy** [comment]
Thanks a lot!
